### ISSUE TITLE
IE8报错，缺少标识符

### ISSUE THREAD

**Issue by chencl1986** [crazyliuzc/webpack-avalon2-SPA-seed#10]
运行npm run dev-hrm后
IE11模拟的IE8中，报错位置如下
SCRIPT1010: 缺少标识符
文件: index.js，行: 1350，列: 22
	  Promise.prototype.catch = function _catch(onRejection) {
	    return this.then(null, onRejection);
	  };

在index.html按照Ant Design的方法添加如下：
    if(!window.Promise) {
      document.writeln('<script src="https://as.alipayobjects.com/g/component/es6-promise/3.2.2/es6-promise.min.js"'+'>'+'<'+'/'+'script>');
    }
依然还是报同样的错

**Comment by crazyliuzc** [comment]
@chencl1986 在IE8中我测是正常的，没有IE11，可能avalon的问题吧，现在avalon作者发言不再更新了，请换框架吧

**Comment by chencl1986** [comment]
太尴尬，已转React
