### ISSUE TITLE
npm run dev-hrm error

### ISSUE THREAD

**Issue by luzhifang** [crazyliuzc/webpack-avalon2-SPA-seed#3]
ERROR in multi common
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\dell\Desk
top\avalon\webpack-avalon2-SPA-seed-master\libs\js\lodash.min.js in C:\Users\del
l\Desktop\avalon\webpack-avalon2-SPA-seed-master
 @ multi common

ERROR in ./src/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\dell\Desk
top\avalon\webpack-avalon2-SPA-seed-master\libs\js\lodash.min.js in C:\Users\del
l\Desktop\avalon\webpack-avalon2-SPA-seed-master\src
 @ ./src/index.js 1:0-17

ERROR in ./src/js/aa/first.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\dell\Desk
top\avalon\webpack-avalon2-SPA-seed-master\libs\js\lodash.min.js in C:\Users\del
l\Desktop\avalon\webpack-avalon2-SPA-seed-master\src\js\aa
 @ ./src/js/aa/first.js 1:0-17

ERROR in ./src/js/bb/second.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\dell\Desk
top\avalon\webpack-avalon2-SPA-seed-master\libs\js\lodash.min.js in C:\Users\del
l\Desktop\avalon\webpack-avalon2-SPA-seed-master\src\js\bb
 @ ./src/js/bb/second.js 1:0-17

ERROR in ./src/js/cc/third.js
Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\dell\Desk
top\avalon\webpack-avalon2-SPA-seed-master\libs\js\lodash.min.js in C:\Users\del
l\Desktop\avalon\webpack-avalon2-SPA-seed-master\src\js\cc
 @ ./src/js/cc/third.js 1:0-17

ERROR in ./src/js/cc/third.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../img/aa/Img41
9362895.jpg in C:\Users\dell\Desktop\avalon\webpack-avalon2-SPA-seed-master\src\
js\cc

**Comment by crazyliuzc** [comment]
哦哦，抱歉，我之前测试用的，忘记提交两个文件
