### ISSUE TITLE
请问跳转后，前一个页面数据没清理这个问题解决了吗？

### ISSUE THREAD

**Issue by cloudus** [crazyliuzc/webpack-avalon2-SPA-seed#4]
使用avalon.modern.js或使用avalon.js路由都可以跳转，但跳转后前个路由页面数据没有统一清除，需要一一重置；

请问这个问题解决了吗

**Comment by crazyliuzc** [comment]
@cloudus 
目前没有好的解决办法，我只能想到：
在路由控件onReady处调用各个vm的制定方法，然后在各自的方法中自己清除。
如果有其它办法请告诉我

**Comment by cloudus** [comment]
我问了正美大大，他说delete vm后不会清理数据的，要一开始吧数据统一整理好，组件退出后删除。

**Comment by cloudus** [comment]
![image](https://cloud.githubusercontent.com/assets/12695053/22054314/eab7fa6c-dd8f-11e6-98c1-89d50d339ef7.png)

![image](https://cloud.githubusercontent.com/assets/12695053/22054273/b1feffc2-dd8f-11e6-9cf9-d996cb0bf4e3.png)

这个是我的想法

**Comment by cloudus** [comment]
可以多多交流哦，我的扣扣202538815

**Comment by crazyliuzc** [comment]
@cloudus 挺好的，我是想着在初始化时加个指定方法清除，在销毁时也挺好
