### ISSUE TITLE
这个项目不能兼容ie8

### ISSUE THREAD

**Issue by twinklexp** [crazyliuzc/webpack-avalon2-SPA-seed#5]
ie8 不兼容 String.prototype.trim 方法，在ie8环境下报SCRIPT438: 对象不支持“trim”属性或方法

**Comment by crazyliuzc** [comment]
@twinklexp 兼容的，是lodash.js的问题，3.10.1版本后不再兼容IE8，换过来就好了

**Comment by twinklexp** [comment]
对的，问题出在lodash.js 和 heredoc.js;
heredoc.js中的trim方法我已经用其他方式替代了。
但是
webpack.config.js 里面配置的lodash是 lodash: path.join(PATHS.libsPath, "js/lodash.min.js"), 已经是3.10.1版本了

**Comment by crazyliuzc** [comment]
@twinklexp 
这……我在IE8下试了，没问题呀
![image](https://cloud.githubusercontent.com/assets/6993730/23601621/60b913c4-0287-11e7-96cc-0682dadbf622.png)

**Comment by twinklexp** [comment]
![qq 20170307221716](https://cloud.githubusercontent.com/assets/17263696/23660413/50dc25e2-0384-11e7-9c5d-1e5f2f1f4708.png)
我目前确实是不可以的，我让同事安装运行也是同样的问题。请问一下你使用的node是什么版本的？

**Comment by hmhao** [comment]
@twinklexp 在index.html加个Polyfill
参考https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by crazyliuzc** [comment]
@twinklexp 和node版本应该没有关系的，我尝试了多个版本没有问题；
如果是lodash问题，可以去掉它，本来这个也只是JS工具插件

**Comment by crazyliuzc** [comment]
@twinklexp 模拟IE8貌似不太好，如果要兼容建议装个虚拟机专门做IE8测试
