### ISSUE TITLE
回退lodash以及加上trim,在IE8下正常运行,但webpack打包之后IE8提示字符串缺失,无法正常运行

### ISSUE THREAD

**Issue by palmerye** [crazyliuzc/webpack-avalon2-SPA-seed#6]
add trim in index.html:
`if (!String.prototype.trim) {
    String.prototype.trim = function () {
        return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, '');
    };
}`
lodash-version: 3.10.1

![image](http://ohce3yxd6.bkt.clouddn.com/github/issue/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20170406155514.png)
![image](http://ohce3yxd6.bkt.clouddn.com/github/issue/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20170406155556.png)
![image](http://ohce3yxd6.bkt.clouddn.com/github/issue/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20170406155543.png)

**Comment by crazyliuzc** [comment]
@palmerye 我看看哦

**Comment by crazyliuzc** [comment]
@palmerye 已经重现问题，是打包时压缩的问题，更新一下项目，或者这里改一下就好了

![minimize](https://cloud.githubusercontent.com/assets/6993730/24749177/b152ae50-1af4-11e7-900f-d4f6f39c21a4.png)

**Comment by palmerye** [comment]
@crazyliuzc 谢谢及时回复！
这个问题应该是webpack压缩代码后，部分格式在IE8下报错吧？比如说末尾的";"?
最近业务场景要在IE8下做SPA，不知道avalon有没有成熟的解决方案？谢谢

**Comment by crazyliuzc** [comment]
@palmerye 很成熟的没有，我已经用这个简单示例项目做SPA，感觉还行，同样问题也不少，用了avalon尽量不要用jquery系列的东西，css在SPA中会冲突，命名要注意

**Comment by palmerye** [comment]
@crazyliuzc css命名冲突?你没有用sass之类的预处理器么?还有一点比较疑惑想请教你,这个工程模块化怎么组织比较好?

**Comment by crazyliuzc** [comment]
http://fex.baidu.com/blog/2014/03/fis-module/
