### ISSUE TITLE
请问如何在路由切换到某一页时调用jquey的方法？

### ISSUE THREAD

**Issue by fefz** [crazyliuzc/webpack-avalon2-SPA-seed#7]
项目中需要集成bootstrap-table，我现在在每个子页面的init方法中使用调用，但是不能正确加载表格，请问应该如何调用？

**Comment by crazyliuzc** [comment]
@codeswing bootstrap-table没有用过，首先要把插件以及样式在webpack.config.js中配置好，子页面JS引入样式，因为
![image](https://cloud.githubusercontent.com/assets/6993730/25077732/235c6c6c-235f-11e7-95ba-e0a35ceadbc6.png)

所以如果插件涉及页面交互，请设置等待时间稍后执行

**Comment by fefz** [comment]
多谢，解决了。
