### ISSUE TITLE
ie8下包router.add()的错

### ISSUE THREAD

**Issue by linsywu** [crazyliuzc/webpack-avalon2-SPA-seed#8]
![image](https://cloud.githubusercontent.com/assets/15061856/25941968/ee8a8aba-366d-11e7-941d-b406012da45f.png)
clone下来项目之后启动在现代浏览器上都ok，到IE8下报错，ie9正常；
loadash有更换成3.10.1版本

**Comment by crazyliuzc** [comment]
@linsywu 
我重新clone了项目在IE8下试了是正常的，是不是修改了什么，请把index.js代码发出来看看
