### ISSUE TITLE
用webpack分割js，avalon里面的vm是个undefined

### ISSUE THREAD

**Issue by crystal001** [crazyliuzc/webpack-avalon2-SPA-seed#9]
我直接down下文件，发现这demo是将所有的js都打包到index.js里面去了，于是我决定分割js，但是	
var vm=require.ensure([],function(){
    	require('./js/aa/first.js');
    });
像这样vm是个undefined，控制台报错
Uncaught TypeError: Cannot read property '$id' of undefined
    at IProxy.onReady (index.js:1217)
    at common.js:1192

**Comment by crazyliuzc** [comment]
@crystal001 
哦哦，为了分割js，我也尝试了好多办法，require.ensure试过的确不行，可能是我水平问题；
目前找到两种办法，相同点都是index.js不需要把所有js、html循环存储了：
1.利用webpack的html-webpack-plugin中的一些事件，如html-webpack-plugin-after-html-processing，在webpack打包的时候更改页面内容，直接拼装好需要的js、css
2.使用avalon提供的[后端渲染](https://github.com/RubyLouvre/avalon-server-render-example)，放弃前端路由，使用nodeJS或其它在服务器渲染好页面再输出，页面布局可以用模版来做，如ejs
